name: CARGO_TARGET_DIR Cache
description: CARGO_TARGET_DIR Cache
runs:
  using: "composite"
  steps:
    - run: rustc --version > rustc_version.txt && cat rustc_version.txt
      shell: bash
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: target
        key: cache-cargo-target-${{ github.workflow }}-${{ github.job }}-ghcr.io/build-trust/ockam-builder@sha256:2b53a00493005871ab31c3e1e4e979fa76e21cd20bbc96773f25bd6b73d2a068-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('./rustc_version.txt') }}
        restore-keys: cache-cargo-target-${{ github.workflow }}-${{ github.job }}-ghcr.io/build-trust/ockam-builder@sha256:2b53a00493005871ab31c3e1e4e979fa76e21cd20bbc96773f25bd6b73d2a068-

# https://doc.rust-lang.org/cargo/guide/build-cache.html
