name: CARGO_TARGET_DIR Cache
description: CARGO_TARGET_DIR Cache
runs:
  using: "composite"
  steps:
    - run: rustc --version > rustc_version.txt && cat rustc_version.txt
      shell: bash
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: target
        key: cache-cargo-target-${{ github.workflow }}-${{ github.job }}-ghcr.io/build-trust/ockam-builder@sha256:55b60f7efe2c48c098bd52db2e9dbf0a1b6f6c7e583ff278987d2d11adea04e2-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('./rustc_version.txt') }}
        restore-keys: cache-cargo-target-${{ github.workflow }}-${{ github.job }}-ghcr.io/build-trust/ockam-builder@sha256:55b60f7efe2c48c098bd52db2e9dbf0a1b6f6c7e583ff278987d2d11adea04e2-

# https://doc.rust-lang.org/cargo/guide/build-cache.html
